
import Footer from './components/footer'

import Navbar from './components/navbar'
import './globals.css'
import { Sora } from 'next/font/google'

const inter = Sora({ subsets: ['latin'] ,
weight:["400" , "500" , "600","700","800"]
})

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        

        {children}</body>
        <Footer/>
    </html>
  )
}
